@JR.AussieQualy.Api_HostAddress = http://localhost:5144

GET {{JR.AussieQualy.Api_HostAddress}}/2026/AUS/drivers
Accept: application/json

###

GET {{JR.AussieQualy.Api_HostAddress}}/2026/aus/q/ALB
Accept: application/json
