<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\JR.AussieQualy.Domain\JR.AussieQualy.Domain.csproj" />
    <ProjectReference Include="..\JR.AussieQualy.Infrastructure\JR.AussieQualy.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
